server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver   #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.athuake.springcloud.entities   #别名

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 入驻地址
  instance:
      instance-id: payment8001
      prefer-ip-address: true   #访问路径可以显示ip地址